version: "3.8"

services:
  dz_telega:
    image: postgres:latest
    container_name: telegram
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=telegram